Fix cargo doc
Summary:
Introduced by D90053903 and D95346214

Issue:
```
error: unresolved link to `Module::freeze`
  --> starlark-rust/starlark/src/environment.rs:23:39
   |
23 | //! [`FrozenModule`] using [`freeze`](Module::freeze) before they can be `load()`'d as a dependency.
   |                                       ^^^^^^^^^^^^^^ the struct `Module` has no field or associated item named `freeze`
   |
   = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(rustdoc::broken_intra_doc_links)]`

error: unresolved link to `StarlarkValue`
   --> starlark-rust/starlark/src/values/layout/avalues/simple.rs:120:29
    |
120 |     /// Allocate a simple [`StarlarkValue`] on this heap.
    |                             ^^^^^^^^^^^^^ no item named `StarlarkValue` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: unresolved link to `StarlarkValue`
   --> starlark-rust/starlark/src/values/layout/avalues/simple.rs:135:29
    |
135 |     /// Allocate a simple [`StarlarkValue`] on this heap.
    |                             ^^^^^^^^^^^^^ no item named `StarlarkValue` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: could not document `starlark`
```

https://github.com/facebook/buck2/actions/runs/25234948756/job/73998956087

___

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: build_infra

Differential Revision: D103479211

fbshipit-source-id: d27c018866c2d223cf11f2459212184ba6483e27